---@alias Color string
---@alias Theme
---| "dark"
---| "light"

---@class Palette
---@field name string
---@field theme Theme
---
---@field background Color
---@field foreground Color
---
---@field primary Color
---@field secondary Color
---
---@field neutral Color
---@field muted Color
---@field grey Color
---
---@field black Color
---@field red Color
---@field green Color
---@field yellow Color
---@field blue Color
---@field magenta Color
---@field cyan Color
---@field white Color
---@field bright_black Color
---@field bright_red Color
---@field bright_green Color
---@field bright_yellow Color
---@field bright_blue Color
---@field bright_magenta Color
---@field bright_cyan Color
---@field bright_white Color
